### POST plotting
POST http://{{host}}:{{port}}/api/qgz
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "selectPath": false,
  "path": "",
  "path3d": "/map/test_data/实景三维/瑞光电厂切片/tileset.json",
  "tileIndex": [
    [
      0,
      0
    ],
    [
      1048576,
      -5821555
    ]
  ],
  "sceneId": "1914619367037911042",
  "sceneName": "修改线面样式 后测试-20250422",
  "geojson": {
    "type": "Feature",
    "geometry": {
      "type": "Polygon",
      "coordinates": [
        [
          [
            112.67923556396747,
            37.75334501717443
          ],
          [
            112.67923556396747,
            37.79012172101295
          ],
          [
            112.7594001674306,
            37.79012172101295
          ],
          [
            112.7594001674306,
            37.75334501717443
          ]
        ]
      ]
    },
    "properties": {}
  },
  "handleFlag": false,
  "sceneType": "04",
  "layinfo": {
    "title": {
      "text": "标题",
      "position": [],
      "borderColor": "",
      "fillColor": "",
      "fontSize": 28,
      "color": "rgba(0,0,0,1)",
      "fontBorderColor": ""
    },
    "subTitle": {
      "text": "",
      "fontSize": 16,
      "color": "rgba(0,0,0,1)"
    },
    "legend": {
      "position": [
        84,
        65,
        16,
        35
      ]
    },
    "bgPic": {
      "borderColor": "#FF0000",
      "doubleFrame": true,
      "borderWidth": 3
    },
    "remark": [
      {
        "text": "备注",
        "position": [
          0,
          80,
          28,
          10
        ],
        "borderColor": "",
        "fillColor": "rgba(255,255,255,1)",
        "fontSize": 18,
        "color": "rgba(0,0,0,1)",
        "url": ""
      }
    ],
    "arrows": [],
    "north": {
      "position": [
        97,
        1,
        2,
        8
      ],
      "rotate": 179
    },
    "scaleBar": false
  },
  "paper": "a3",
  "pictureUnit": "制图单位：    时间：",
  "mapType": {
    "map": true,
    "electron": false,
    "is3D": true
  },
  "camera": {
    "cameraLongitude": 112.72036493562986,
    "cameraLatitude": 37.806336132063066,
    "cameraHeight": 2507.5393432896635,
    "cameraDirX": 0.01694088623947776,
    "cameraDirY": -0.00841959450515789,
    "cameraDirZ": -0.9998210423879815,
    "cameraUpX": -0.37704852639974096,
    "cameraUpY": 0.9260848386057254,
    "cameraUpZ": -0.01418733394233906,
    "cameraRightX": 0.9260385602733857,
    "cameraRightY": 0.3772213967062,
    "cameraRightZ": 0.012514102197871576,
    "fov": 1.0471975511965976,
    "aspectRatio": 2.10989010989011,
    "nearPlane": 0.1,
    "farPlane": 10000000000,
    "centerLongitude": 112.71980048140705,
    "centerLatitude": 37.77805355231326,
    "centerHeight": 871.7572173188173,
    "heading": "180.91",
    "pitch": "-38.62",
    "roll": "0.00"
  }
}
### Response
HTTP/1.1 200 OK
Server: TornadoServer/6.4.1
Content-Type: application/json; charset=UTF-8
Date: Thu, 07 Nov 2024 07:12:42 GMT
Content-Length: 141

{
  "project_zip_url": "http://localhost:80/jingweipy/test.zip",
  "image_url": "http://localhost:80/jingweipy/local/test-位置图.png"
}
###
