### POST plotting
POST http://{{host}}:{{port}}/api/qgz
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "selectPath": false,
  "path": "",
  "path3d": "/map/mnt/fakeRoot/data/mapdata/3DTiles/瑞光电厂OSGB切片/tileset.json",
  "tileIndex": [
    [
      0,
      0
    ],
    [
      1048576,
      -5821555
    ]
  ],
  "sceneId": "1933800942803283970",
  "sceneName": "瑞光电厂",
  "geojson": {
    "type": "Feature",
    "geometry": {
      "type": "Polygon",
      "coordinates": [
        [
          [
            112.6227265256816,
            37.78006892281279
          ],
          [
            112.6227265256816,
            37.871754426324934
          ],
          [
            112.72985102829593,
            37.871754426324934
          ],
          [
            112.72985102829593,
            37.78006892281279
          ]
        ]
      ]
    },
    "properties": {}
  },
  "handleFlag": false,
  "sceneType": "undefined",
  "layinfo": {
    "title": {
      "text": "标题",
      "position": [],
      "borderColor": "",
      "fillColor": "",
      "fontSize": 28,
      "color": "rgba(0,0,0,1)",
      "fontBorderColor": ""
    },
    "subTitle": {
      "text": "",
      "fontSize": 16,
      "color": "rgba(0,0,0,1)"
    },
    "legend": {
      "position": [
        84,
        65,
        16,
        35
      ]
    },
    "bgPic": {
      "borderColor": "#FF0000",
      "doubleFrame": true,
      "borderWidth": 3
    },
    "remark": [
      {
        "text": "备注",
        "position": [
          0,
          80,
          28,
          10
        ],
        "borderColor": "",
        "fillColor": "rgba(255,255,255,1)",
        "fontSize": 18,
        "color": "rgba(0,0,0,1)",
        "url": ""
      }
    ],
    "arrows": [],
    "north": {
      "position": [
        97,
        1,
        2,
        8
      ],
      "rotate": 32
    },
    "scaleBar": false
  },
  "paper": "a3",
  "pictureUnit": "制图单位：    时间：",
  "mapType": {
    "map": true,
    "electron": false,
    "is3D": true
  },
  "camera": {
    "cameraLongitude": 112.72685658740096,
    "cameraLatitude": 37.77665720895643,
    "cameraHeight": 1460.13806189497,
    "cameraDirX": 0.7449057963070019,
    "cameraDirY": -0.6193177327377665,
    "cameraDirZ": 0.2481146923194672,
    "cameraUpX": 0.10258606235572178,
    "cameraUpY": 0.473792662237761,
    "cameraUpZ": 0.8746408480170607,
    "cameraRightX": -0.6592355075681067,
    "cameraRightY": -0.6260719280771244,
    "cameraRightZ": 0.4164642678972744,
    "fov": 1.0471975511965976,
    "aspectRatio": 1.37108953613808,
    "nearPlane": 0.1,
    "farPlane": 10000000000,
    "centerLongitude": 112.7127651702561,
    "centerLatitude": 37.79469372484934,
    "centerHeight": 897.1341262677532,
    "heading": "328.20",
    "pitch": "-31.80",
    "roll": "0.00"
  },
  "clarity": 800
}

### Response
HTTP/1.1 200 OK
Server: TornadoServer/6.4.1
Content-Type: application/json; charset=UTF-8
Date: Thu, 07 Nov 2024 07:12:42 GMT
Content-Length: 141

{
  "project_zip_url": "http://localhost:80/jingweipy/test.zip",
  "image_url": "http://localhost:80/jingweipy/local/test-位置图.png"
}
###
