### POST plotting
POST http://{{host}}:{{port}}/api/qgz
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "selectPath": false,
  "path": "",
  "path3d": "/map/mnt/fakeRoot/data/mapdata/3DTiles/瑞光电厂OSGB切片/tileset.json",
  "tileIndex": [
    [
      0,
      0
    ],
    [
      1048576,
      -5821555
    ]
  ],
  "sceneId": "1937796764201562113",
  "sceneName": "多个地方11",
  "geojson": {
    "type": "Feature",
    "geometry": {
      "type": "Polygon",
      "coordinates": [
        [
          [
            112.67597508761678,
            37.781273139782606
          ],
          [
            112.67597508761678,
            37.834828102781835
          ],
          [
            112.76533782335784,
            37.834828102781835
          ],
          [
            112.76533782335784,
            37.781273139782606
          ]
        ]
      ]
    },
    "properties": {}
  },
  "handleFlag": false,
  "sceneType": "undefined",
  "layinfo": {
    "title": {
      "text": "标题",
      "position": [],
      "borderColor": "",
      "fillColor": "",
      "fontSize": 28,
      "color": "rgba(0,0,0,1)",
      "fontBorderColor": ""
    },
    "subTitle": {
      "text": "",
      "fontSize": 16,
      "color": "rgba(0,0,0,1)"
    },
    "legend": {
      "position": [
        84,
        65,
        16,
        35
      ]
    },
    "bgPic": {
      "borderColor": "#FF0000",
      "doubleFrame": true,
      "borderWidth": 3
    },
    "remark": [
      {
        "text": "备注",
        "position": [
          0,
          80,
          28,
          10
        ],
        "borderColor": "",
        "fillColor": "rgba(255,255,255,1)",
        "fontSize": 18,
        "color": "rgba(0,0,0,1)",
        "url": ""
      }
    ],
    "arrows": [],
    "north": {
      "position": [
        97,
        1,
        2,
        8
      ],
      "rotate": 0
    },
    "scaleBar": false
  },
  "paper": "a3",
  "pictureUnit": "制图单位：    时间：",
  "mapType": {
    "map": true,
    "electron": false,
    "is3D": true
  },
  "camera": {
    "cameraLongitude": 112.72065645530303,
    "cameraLatitude": 37.771209077494646,
    "cameraHeight": 2178.12111863811,
    "cameraDirX": 0.3774950185458905,
    "cameraDirY": -0.9015178135008075,
    "cameraDirZ": 0.21157302028793967,
    "cameraUpX": -0.08171767002743413,
    "cameraUpY": 0.1951547214879727,
    "cameraUpZ": 0.9773621933992737,
    "cameraRightX": -0.9223989014403287,
    "cameraRightY": -0.3862386135819085,
    "cameraRightZ": -9.25370891025068e-14,
    "fov": 1.0471975511965976,
    "aspectRatio": 1.37108953613808,
    "nearPlane": 0.1,
    "farPlane": 10000000000,
    "centerLongitude": 112.72065645527537,
    "centerLatitude": 37.794590005537685,
    "centerHeight": 916.6617756483026,
    "heading": "0.00",
    "pitch": "-40.01",
    "roll": "360.00"
  },
  "clarity": 800
}

### Response

###