### POST plotting
POST http://{{host}}:{{port}}/api/qgz
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "selectPath": false,
  "path": "",
  "path3d": "/map/test_data/实景三维/瑞光电厂切片/tileset.json",
  "tileIndex": [
    [
      0,
      0
    ],
    [
      1048576,
      -5821555
    ]
  ],
  "sceneId": "1914619367037911042",
  "sceneName": "修改线面样式 后测试-20250422",
  "geojson": {
    "type": "Feature",
    "geometry": {
      "type": "Polygon",
      "coordinates": [
        [
          [
            112.67669698405837,
            37.78164075262421
          ],
          [
            112.67669698405837,
            37.820425927936704
          ],
          [
            112.76461592696866,
            37.820425927936704
          ],
          [
            112.76461592696866,
            37.78164075262421
          ]
        ]
      ]
    },
    "properties": {}
  },
  "handleFlag": false,
  "sceneType": "04",
  "layinfo": {
    "title": {
      "text": "标题",
      "position": [],
      "borderColor": "",
      "fillColor": "",
      "fontSize": 28,
      "color": "rgba(0,0,0,1)",
      "fontBorderColor": ""
    },
    "subTitle": {
      "text": "",
      "fontSize": 16,
      "color": "rgba(0,0,0,1)"
    },
    "legend": {
      "position": [
        84,
        65,
        16,
        35
      ]
    },
    "bgPic": {
      "borderColor": "#FF0000",
      "doubleFrame": true,
      "borderWidth": 3
    },
    "remark": [
      {
        "text": "备注",
        "position": [
          0,
          80,
          28,
          10
        ],
        "borderColor": "",
        "fillColor": "rgba(255,255,255,1)",
        "fontSize": 18,
        "color": "rgba(0,0,0,1)",
        "url": ""
      }
    ],
    "arrows": [],
    "north": {
      "position": [
        97,
        1,
        2,
        8
      ],
      "rotate": 0
    },
    "scaleBar": false
  },
  "paper": "a3",
  "pictureUnit": "制图单位：    时间：",
  "mapType": {
    "map": true,
    "electron": false,
    "is3D": true
  },
  "camera": {
    "cameraLongitude": 112.72065645530304,
    "cameraLatitude": 37.76355205413761,
    "cameraHeight": 2901.990351242898,
    "cameraDirX": 0.37749501896347565,
    "cameraDirY": -0.9015178144978987,
    "cameraDirZ": 0.2115730152942418,
    "cameraUpX": -0.08171766809862513,
    "cameraUpY": 0.19515471688181274,
    "cameraUpZ": 0.9773621944802768,
    "cameraRightX": -0.9223989014403086,
    "cameraRightY": -0.3862386135819565,
    "cameraRightZ": -2.556288514199423e-14,
    "fov": 1.0471975511965976,
    "aspectRatio": 2.10989010989011,
    "nearPlane": 0.1,
    "farPlane": 10000000000,
    "centerLongitude": 112.72065645526618,
    "centerLatitude": 37.79469739836375,
    "centerHeight": 916.7779084472597,
    "heading": "0.00",
    "pitch": "-40.02",
    "roll": "360.00"
  }
}
### Response
HTTP/1.1 200 OK
Server: TornadoServer/6.4.1
Content-Type: application/json; charset=UTF-8
Date: Thu, 07 Nov 2024 07:12:42 GMT
Content-Length: 141

{
  "project_zip_url": "http://localhost:80/jingweipy/test.zip",
  "image_url": "http://localhost:80/jingweipy/local/test-位置图.png"
}
###
