### POST plotting
POST http://{{host}}:{{port}}/api/qgz
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "selectPath": false,
  "path": "",
  "path3d": "/map/test_data/实景三维/瑞光电厂切片/tileset.json",
  "tileIndex": [
    [
      0,
      0
    ],
    [
      1048576,
      -5821555
    ]
  ],
  "sceneId": "1914619367037911042",
  "sceneName": "修改线面样式 后测试-20250422",
  "geojson": {
    "type": "Feature",
    "geometry": {
      "type": "Polygon",
      "coordinates": [
        [
          [
            112.72575569523732,
            37.73491374636676
          ],
          [
            112.72575569523732,
            37.85083832265714
          ],
          [
            112.84509845353874,
            37.85083832265714
          ],
          [
            112.84509845353874,
            37.73491374636676
          ]
        ]
      ]
    },
    "properties": {}
  },
  "handleFlag": false,
  "sceneType": "04",
  "layinfo": {
    "title": {
      "text": "标题",
      "position": [],
      "borderColor": "",
      "fillColor": "",
      "fontSize": 28,
      "color": "rgba(0,0,0,1)",
      "fontBorderColor": ""
    },
    "subTitle": {
      "text": "",
      "fontSize": 16,
      "color": "rgba(0,0,0,1)"
    },
    "legend": {
      "position": [
        84,
        65,
        16,
        35
      ]
    },
    "bgPic": {
      "borderColor": "#FF0000",
      "doubleFrame": true,
      "borderWidth": 3
    },
    "remark": [
      {
        "text": "备注",
        "position": [
          0,
          80,
          28,
          10
        ],
        "borderColor": "",
        "fillColor": "rgba(255,255,255,1)",
        "fontSize": 18,
        "color": "rgba(0,0,0,1)",
        "url": ""
      }
    ],
    "arrows": [],
    "north": {
      "position": [
        97,
        1,
        2,
        8
      ],
      "rotate": 275
    },
    "scaleBar": false
  },
  "paper": "a3",
  "pictureUnit": "制图单位：    时间：",
  "mapType": {
    "map": true,
    "electron": false,
    "is3D": true
  },
  "camera": {
    "cameraLongitude": 112.70894103616509,
    "cameraLatitude": 37.78459807912203,
    "cameraHeight": 1160.5080108944821,
    "cameraDirX": -0.7301310570559079,
    "cameraDirY": -0.6639042454282983,
    "cameraDirZ": -0.16167805177173764,
    "cameraUpX": -0.609122037420313,
    "cameraUpY": 0.5251595415789548,
    "cameraUpZ": 0.5942876403035057,
    "cameraRightX": -0.3096433158512386,
    "cameraRightY": 0.5323895273114073,
    "cameraRightZ": -0.7878339978433186,
    "fov": 1.0471975511965976,
    "aspectRatio": 2.10989010989011,
    "nearPlane": 0.1,
    "farPlane": 10000000000,
    "centerLongitude": 112.7429603963257,
    "centerLatitude": 37.7867639305579,
    "centerHeight": 930.2560378474843,
    "heading": "85.40",
    "pitch": "-21.12",
    "roll": "0.01"
  }
}
### Response
HTTP/1.1 200 OK
Server: TornadoServer/6.4.1
Content-Type: application/json; charset=UTF-8
Date: Thu, 07 Nov 2024 07:12:42 GMT
Content-Length: 141

{
  "project_zip_url": "http://localhost:80/jingweipy/test.zip",
  "image_url": "http://localhost:80/jingweipy/local/test-位置图.png"
}
###
