### POST plotting
POST http://{{host}}:{{port}}/api/qgz
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "clarity": 1,
  "selectPath": false,
  "path": "",
  "path3d": "/map/mnt/fakeRoot/data/mapdata/瑞光电厂OSGB切片/tileset.json",
  "tileIndex": [
    [
      0,
      0
    ],
    [
      1048576,
      -5821555
    ]
  ],
  "sceneId": "1931962881837010945",
  "sceneName": "ces",
  "geojson": {
    "type": "Feature",
    "geometry": {
      "type": "Polygon",
      "coordinates": [
        [
          [
            112.71874841163428,
            37.78464083106351
          ],
          [
            112.71874841163428,
            37.844953184983964
          ],
          [
            112.7949486084908,
            37.844953184983964
          ],
          [
            112.7949486084908,
            37.78464083106351
          ]
        ]
      ]
    },
    "properties": {}
  },
  "handleFlag": false,
  "sceneType": "undefined",
  "layinfo": {
    "title": {
      "text": "标题",
      "position": [],
      "borderColor": "",
      "fillColor": "",
      "fontSize": 28,
      "color": "rgba(0,0,0,1)",
      "fontBorderColor": ""
    },
    "subTitle": {
      "text": "",
      "fontSize": 16,
      "color": "rgba(0,0,0,1)"
    },
    "legend": {
      "position": [
        84,
        65,
        16,
        35
      ]
    },
    "bgPic": {
      "borderColor": "#FF0000",
      "doubleFrame": true,
      "borderWidth": 3
    },
    "remark": [
      {
        "text": "备注",
        "position": [
          0,
          80,
          28,
          10
        ],
        "borderColor": "",
        "fillColor": "rgba(255,255,255,1)",
        "fontSize": 18,
        "color": "rgba(0,0,0,1)",
        "url": ""
      }
    ],
    "arrows": [],
    "north": {
      "position": [
        97,
        1,
        2,
        8
      ],
      "rotate": 315
    },
    "scaleBar": false
  },
  "paper": "a3",
  "pictureUnit": "制图单位：    时间：",
  "mapType": {
    "map": true,
    "electron": false,
    "is3D": true
  },
  "camera": {
    "cameraLongitude": 112.71824956472598,
    "cameraLatitude": 37.7843475296414,
    "cameraHeight": 901.2943491467621,
    "cameraDirX": -0.25917221763433324,
    "cameraDirY": -0.9534361253237793,
    "cameraDirZ": 0.15423785700689832,
    "cameraUpX": -0.5160660660494153,
    "cameraUpY": 0.2716910914449437,
    "cameraUpZ": 0.8123175280035116,
    "cameraRightX": -0.8163979281445921,
    "cameraRightY": 0.13093321105446745,
    "cameraRightZ": -0.5624508131065186,
    "fov": 1.0471975511965976,
    "aspectRatio": 1.3516720604099244,
    "nearPlane": 0.1,
    "farPlane": 10000000000,
    "centerLongitude": 112.7301689801597,
    "centerLatitude": 37.79368299444815,
    "centerHeight": 914.0331121616787,
    "heading": "45.37",
    "pitch": "-31.43",
    "roll": "360.00"
  }
}

### Response
HTTP/1.1 200 OK
Server: TornadoServer/6.4.1
Content-Type: application/json; charset=UTF-8
Date: Thu, 07 Nov 2024 07:12:42 GMT
Content-Length: 141

{
  "project_zip_url": "http://localhost:80/jingweipy/test.zip",
  "image_url": "http://localhost:80/jingweipy/local/test-位置图.png"
}
###
