### POST plotting
POST http://{{host}}:{{port}}/api/qgz
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "selectPath": true,
  "path": "/map/test_data/正射/瑞光电厂-DOM",
  "tileIndex": [
    [
      0,
      0
    ],
    [
      1048576,
      -5821555
    ]
  ],
  "sceneId": "1897221438304206849",
  "sceneName": "高速20250227_g_ys",
  "geojson": {
    "type": "Feature",
    "geometry": {
      "type": "Polygon",
      "coordinates": [
        [
          [
            112.69858601628759,
            37.7775647250668
          ],
          [
            112.69858601628759,
            37.79300198197764
          ],
          [
            112.73922826568773,
            37.79300198197764
          ],
          [
            112.73922826568773,
            37.7775647250668
          ]
        ]
      ]
    },
    "properties": { }
  },
  "handleFlag": false,
  "sceneType": "01",
  "layinfo": {
    "title": {
      "text": "标题",
      "position": [ ],
      "borderColor": "",
      "fillColor": "",
      "fontSize": 28,
      "color": "rgba(0,0,0,1)",
      "fontBorderColor": ""
    },
    "subTitle": {
      "text": "",
      "fontSize": 16,
      "color": "rgba(0,0,0,1)"
    },
    "legend": {
      "position": [
        84,
        20,
        46,
        80
      ]
    },
    "bgPic": {
      "borderColor": "#FF0000",
      "doubleFrame": true,
      "borderWidth": 3
    },
    "remark": [
      {
        "text": "备注",
        "position": [
          0,
          80,
          28,
          10
        ],
        "borderColor": "",
        "fillColor": "rgba(255,255,255,1)",
        "fontSize": 18,
        "color": "rgba(0,0,0,1)",
        "url": ""
      }
    ],
    "arrows": [ ],
    "north": {
      "position": [
        97,
        1,
        2,
        8
      ],
      "rotate": 0
    },
    "scaleBar": true
  },
  "paper": "a3",
  "pictureUnit": "制图单位： 时间：",
  "mapType": {
    "map": true,
    "electron": false
  }
}

### Response
HTTP/1.1 200 OK
Server: TornadoServer/6.4.1
Content-Type: application/json; charset=UTF-8
Date: Thu, 07 Nov 2024 07:12:42 GMT
Content-Length: 141

{
  "project_zip_url": "http://localhost:80/jingweipy/test.zip",
  "image_url": "http://localhost:80/jingweipy/local/test-位置图.png"
}
###
