### POST plotting
POST http://{{host}}:{{port}}/api/qgz
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "selectPath": false,
  "path": "",
  "path3d": "/map/mnt/fakeRoot/data/mapdata/3DTiles/瑞光电厂OSGB切片/tileset.json",
  "tileIndex": [
    [
      0,
      0
    ],
    [
      1048576,
      -5821555
    ]
  ],
  "sceneId": "1933800942803283970",
  "sceneName": "瑞光电厂",
  "geojson": {
    "type": "Feature",
    "geometry": {
      "type": "Polygon",
      "coordinates": [
        [
          [
            111.50540891017432,
            37.78823712050634
          ],
          [
            111.50540891017432,
            38.72989666117149
          ],
          [
            113.94496616203752,
            38.72989666117149
          ],
          [
            113.94496616203752,
            37.78823712050634
          ]
        ]
      ]
    },
    "properties": {}
  },
  "handleFlag": false,
  "sceneType": "undefined",
  "layinfo": {
    "title": {
      "text": "标题",
      "position": [],
      "borderColor": "",
      "fillColor": "",
      "fontSize": 28,
      "color": "rgba(0,0,0,1)",
      "fontBorderColor": ""
    },
    "subTitle": {
      "text": "",
      "fontSize": 16,
      "color": "rgba(0,0,0,1)"
    },
    "legend": {
      "position": [
        84,
        65,
        16,
        35
      ]
    },
    "bgPic": {
      "borderColor": "#FF0000",
      "doubleFrame": true,
      "borderWidth": 3
    },
    "remark": [
      {
        "text": "备注",
        "position": [
          0,
          80,
          28,
          10
        ],
        "borderColor": "",
        "fillColor": "rgba(255,255,255,1)",
        "fontSize": 18,
        "color": "rgba(0,0,0,1)",
        "url": ""
      }
    ],
    "arrows": [],
    "north": {
      "position": [
        97,
        1,
        2,
        8
      ],
      "rotate": 48
    },
    "scaleBar": false
  },
  "paper": "a3",
  "pictureUnit": "制图单位：    时间：",
  "mapType": {
    "map": true,
    "electron": false,
    "is3D": true
  },
  "camera": {
    "cameraLongitude": 112.72518753610592,
    "cameraLatitude": 37.78257642326537,
    "cameraHeight": 881.0958511528044,
    "cameraDirX": 0.8568701352985848,
    "cameraDirY": -0.12314172375971465,
    "cameraDirZ": 0.5006093158370819,
    "cameraUpX": -0.2673002380199765,
    "cameraUpY": 0.7242070374580003,
    "cameraUpZ": 0.6356687420746521,
    "cameraRightX": -0.44082213418549154,
    "cameraRightY": -0.6784985503048578,
    "cameraRightZ": 0.587635570099662,
    "fov": 1.0471975511965976,
    "aspectRatio": 2.071197411003236,
    "nearPlane": 0.1,
    "farPlane": 10000000000,
    "centerLongitude": 112.55244048895071,
    "centerLatitude": 37.905553268392026,
    "centerHeight": 812.1752593944888,
    "heading": "311.97",
    "pitch": "-2.56",
    "roll": "360.00"
  },
  "clarity": 800
}
### Response
HTTP/1.1 200 OK
Server: TornadoServer/6.4.1
Content-Type: application/json; charset=UTF-8
Date: Thu, 07 Nov 2024 07:12:42 GMT
Content-Length: 141

{
  "project_zip_url": "http://localhost:80/jingweipy/test.zip",
  "image_url": "http://localhost:80/jingweipy/local/test-位置图.png"
}
###
