### POST plotting
POST http://{{host}}:{{port}}/api/qgz
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "selectPath": false,
  "path": "",
  "path3d": "/map/test_data/实景三维/瑞光电厂切片/tileset.json",
  "tileIndex": [
    [
      0,
      0
    ],
    [
      1048576,
      -5821555
    ]
  ],
  "sceneId": "1914619367037911042",
  "sceneName": "修改线面样式后测试-20250422",
  "geojson": {
    "type": "Feature",
    "geometry": {
      "type": "Polygon",
      "coordinates": [
        [
          [
            112.7124572491385,
            37.77130626190145
          ],
          [
            112.7124572491385,
            37.799245818669604
          ],
          [
            112.73008127623568,
            37.799245818669604
          ],
          [
            112.73008127623568,
            37.77130626190145
          ]
        ]
      ]
    },
    "properties": {}
  },
  "handleFlag": false,
  "sceneType": "04",
  "layinfo": {
    "title": {
      "text": "标题",
      "position": [],
      "borderColor": "",
      "fillColor": "",
      "fontSize": 28,
      "color": "rgba(0,0,0,1)",
      "fontBorderColor": ""
    },
    "subTitle": {
      "text": "",
      "fontSize": 16,
      "color": "rgba(0,0,0,1)"
    },
    "legend": {
      "position": [
        84,
        65,
        16,
        35
      ]
    },
    "bgPic": {
      "borderColor": "#FF0000",
      "doubleFrame": true,
      "borderWidth": 3
    },
    "remark": [
      {
        "text": "备注",
        "position": [
          0,
          80,
          28,
          10
        ],
        "borderColor": "",
        "fillColor": "rgba(255,255,255,1)",
        "fontSize": 18,
        "color": "rgba(0,0,0,1)",
        "url": ""
      }
    ],
    "arrows": [],
    "north": {
      "position": [
        97,
        1,
        2,
        8
      ],
      "rotate": 268
    },
    "scaleBar": false
  },
  "paper": "a3",
  "pictureUnit": "制图单位：    时间：",
  "mapType": {
    "map": true,
    "electron": false,
    "is3D": true
  },
  "camera": {
    "cameraLongitude": 112.72048662247168,
    "cameraLatitude": 37.78538680862525,
    "cameraHeight": 2643.26520800427,
    "cameraDirX": 0.28276854018932884,
    "cameraDirY": -0.7376288193132818,
    "cameraDirZ": -0.6131440920352164,
    "cameraUpX": -0.9370109215727149,
    "cameraUpY": -0.34908811429477726,
    "cameraUpZ": -0.012166400929114234,
    "cameraRightX": -0.2050670269269225,
    "cameraRightY": 0.5779629861648674,
    "cameraRightZ": -0.7898773962399115,
    "fov": 1.0471975511965976,
    "aspectRatio": 2.1075740944017562,
    "nearPlane": 0.1,
    "farPlane": 10000000000,
    "centerLongitude": 112.7212091944271,
    "centerLatitude": 37.78536822874182,
    "centerHeight": 892.8280221415599,
    "heading": "91.95",
    "pitch": "-88.62",
    "roll": "0.00"
  }
}
### Response
HTTP/1.1 200 OK
Server: TornadoServer/6.4.1
Content-Type: application/json; charset=UTF-8
Date: Thu, 07 Nov 2024 07:12:42 GMT
Content-Length: 141

{
  "project_zip_url": "http://localhost:80/jingweipy/test.zip",
  "image_url": "http://localhost:80/jingweipy/local/test-位置图.png"
}
###
