### POST plotting
POST http://{{host}}:{{port}}/api/qgz
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "selectPath": false,
  "path": "",
  "path3d": "/map/mnt/fakeRoot/data/mapdata/3DTiles/瑞光电厂OSGB切片/tileset.json",
  "tileIndex": [
    [
      0,
      0
    ],
    [
      1048576,
      -5821555
    ]
  ],
  "sceneId": "1933800942803283970",
  "sceneName": "瑞光电厂",
  "geojson": {
    "type": "Feature",
    "geometry": {
      "type": "Polygon",
      "coordinates": [
        [
          [
            111.39605654959736,
            37.78847160667225
          ],
          [
            111.39605654959736,
            38.80712776726336
          ],
          [
            114.05062161569678,
            38.80712776726336
          ],
          [
            114.05062161569678,
            37.78847160667225
          ]
        ]
      ]
    },
    "properties": {}
  },
  "handleFlag": false,
  "sceneType": "undefined",
  "layinfo": {
    "title": {
      "text": "标题",
      "position": [],
      "borderColor": "",
      "fillColor": "",
      "fontSize": 28,
      "color": "rgba(0,0,0,1)",
      "fontBorderColor": ""
    },
    "subTitle": {
      "text": "",
      "fontSize": 16,
      "color": "rgba(0,0,0,1)"
    },
    "legend": {
      "position": [
        84,
        65,
        16,
        35
      ]
    },
    "bgPic": {
      "borderColor": "#FF0000",
      "doubleFrame": true,
      "borderWidth": 3
    },
    "remark": [
      {
        "text": "备注",
        "position": [
          0,
          80,
          28,
          10
        ],
        "borderColor": "",
        "fillColor": "rgba(255,255,255,1)",
        "fontSize": 18,
        "color": "rgba(0,0,0,1)",
        "url": ""
      }
    ],
    "arrows": [],
    "north": {
      "position": [
        97,
        1,
        2,
        8
      ],
      "rotate": 18
    },
    "scaleBar": false
  },
  "paper": "a3",
  "pictureUnit": "制图单位：    时间：",
  "mapType": {
    "map": true,
    "electron": false,
    "is3D": true
  },
  "camera": {
    "cameraLongitude": 112.72333908264707,
    "cameraLatitude": 37.778031249650184,
    "cameraHeight": 1041.0642959581116,
    "cameraDirX": 0.5647621741809287,
    "cameraDirY": -0.5456883538087187,
    "cameraDirZ": 0.619086348688098,
    "cameraUpX": -0.20114960595571868,
    "cameraUpY": 0.6365278946720349,
    "cameraUpZ": 0.7445609950354949,
    "cameraRightX": -0.8003639938417328,
    "cameraRightY": -0.5450288614577372,
    "cameraRightZ": 0.24972188037853893,
    "fov": 1.0471975511965976,
    "aspectRatio": 1.37108953613808,
    "nearPlane": 0.1,
    "farPlane": 10000000000,
    "centerLongitude": 112.70409754226041,
    "centerLatitude": 37.823862465217445,
    "centerHeight": 1093.7697042123514,
    "heading": "341.58",
    "pitch": "-11.01",
    "roll": "0.00"
  },
  "clarity": 800
}

### Response
HTTP/1.1 200 OK
Server: TornadoServer/6.4.1
Content-Type: application/json; charset=UTF-8
Date: Thu, 07 Nov 2024 07:12:42 GMT
Content-Length: 141

{
  "project_zip_url": "http://localhost:80/jingweipy/test.zip",
  "image_url": "http://localhost:80/jingweipy/local/test-位置图.png"
}
###
