### POST plotting
POST http://{{host}}:{{port}}/api/qgz
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "selectPath": false,
  "path": "",
  "path3d": "/map/mnt/fakeRoot/data/mapdata/3DTiles/瑞光电厂OSGB切片/tileset.json",
  "tileIndex": [
    [
      0,
      0
    ],
    [
      1048576,
      -5821555
    ]
  ],
  "sceneId": "1933800942803283970",
  "sceneName": "瑞光电厂",
  "geojson": {
    "type": "Feature",
    "geometry": {
      "type": "Polygon",
      "coordinates": [
        [
          [
            112.70255046516374,
            37.77711463670043
          ],
          [
            112.70255046516374,
            37.79785739182137
          ],
          [
            112.73776496693549,
            37.79785739182137
          ],
          [
            112.73776496693549,
            37.77711463670043
          ]
        ]
      ]
    },
    "properties": {}
  },
  "handleFlag": false,
  "sceneType": "undefined",
  "layinfo": {
    "title": {
      "text": "标题",
      "position": [],
      "borderColor": "",
      "fillColor": "",
      "fontSize": 28,
      "color": "rgba(0,0,0,1)",
      "fontBorderColor": ""
    },
    "subTitle": {
      "text": "",
      "fontSize": 16,
      "color": "rgba(0,0,0,1)"
    },
    "legend": {
      "position": [
        84,
        65,
        16,
        35
      ]
    },
    "bgPic": {
      "borderColor": "#FF0000",
      "doubleFrame": true,
      "borderWidth": 3
    },
    "remark": [
      {
        "text": "备注",
        "position": [
          0,
          80,
          28,
          10
        ],
        "borderColor": "",
        "fillColor": "rgba(255,255,255,1)",
        "fontSize": 18,
        "color": "rgba(0,0,0,1)",
        "url": ""
      }
    ],
    "arrows": [],
    "north": {
      "position": [
        97,
        1,
        2,
        8
      ],
      "rotate": 358
    },
    "scaleBar": false
  },
  "paper": "a3",
  "pictureUnit": "制图单位：    时间：",
  "mapType": {
    "map": true,
    "electron": false,
    "is3D": true
  },
  "camera": {
    "cameraLongitude": 112.7195355221125,
    "cameraLatitude": 37.78483912832974,
    "cameraHeight": 2566.783956359624,
    "cameraDirX": 0.32303505739166016,
    "cameraDirY": -0.7812481040714052,
    "cameraDirZ": -0.5341345818993578,
    "cameraUpX": 0.16963328802281274,
    "cameraUpY": -0.5074546848766878,
    "cameraUpZ": 0.8448161281552755,
    "cameraRightX": -0.9310600943497342,
    "cameraRightY": -0.36351223181831793,
    "cameraRightZ": -0.03139996859758659,
    "fov": 1.0471975511965976,
    "aspectRatio": 1.37108953613808,
    "nearPlane": 0.1,
    "farPlane": 10000000000,
    "centerLongitude": 112.71964572515368,
    "centerLatitude": 37.78706562178083,
    "centerHeight": 897.8381335864912,
    "heading": "2.25",
    "pitch": "-84.50",
    "roll": "0.03"
  },
  "clarity": 800
}
### Response
HTTP/1.1 200 OK
Server: TornadoServer/6.4.1
Content-Type: application/json; charset=UTF-8
Date: Thu, 07 Nov 2024 07:12:42 GMT
Content-Length: 141

{
  "project_zip_url": "http://localhost:80/jingweipy/test.zip",
  "image_url": "http://localhost:80/jingweipy/local/test-位置图.png"
}
###
