### POST plotting
POST http://{{host}}:{{port}}/api/qgz
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "selectPath": false,
  "path": "",
  "path3d": "/map/mnt/fakeRoot/data/mapdata/3DTiles/瑞光电厂OSGB切片/tileset.json",
  "tileIndex": [
    [
      0,
      0
    ],
    [
      1048576,
      -5821555
    ]
  ],
  "sceneId": "1933800942803283970",
  "sceneName": "瑞光电厂",
  "geojson": {
    "type": "Feature",
    "geometry": {
      "type": "Polygon",
      "coordinates": [
        [
          [
            111.28425237419509,
            37.78117033013226
          ],
          [
            111.28425237419509,
            38.89357168569318
          ],
          [
            114.1718753913802,
            38.89357168569318
          ],
          [
            114.1718753913802,
            37.78117033013226
          ]
        ]
      ]
    },
    "properties": {}
  },
  "handleFlag": false,
  "sceneType": "undefined",
  "layinfo": {
    "title": {
      "text": "标题",
      "position": [],
      "borderColor": "",
      "fillColor": "",
      "fontSize": 28,
      "color": "rgba(0,0,0,1)",
      "fontBorderColor": ""
    },
    "subTitle": {
      "text": "",
      "fontSize": 16,
      "color": "rgba(0,0,0,1)"
    },
    "legend": {
      "position": [
        84,
        65,
        16,
        35
      ]
    },
    "bgPic": {
      "borderColor": "#FF0000",
      "doubleFrame": true,
      "borderWidth": 3
    },
    "remark": [
      {
        "text": "备注",
        "position": [
          0,
          80,
          28,
          10
        ],
        "borderColor": "",
        "fillColor": "rgba(255,255,255,1)",
        "fontSize": 18,
        "color": "rgba(0,0,0,1)",
        "url": ""
      }
    ],
    "arrows": [],
    "north": {
      "position": [
        97,
        1,
        2,
        8
      ],
      "rotate": 35
    },
    "scaleBar": false
  },
  "paper": "a3",
  "pictureUnit": "制图单位：    时间：",
  "mapType": {
    "map": true,
    "electron": false,
    "is3D": true
  },
  "camera": {
    "cameraLongitude": 112.72806388278765,
    "cameraLatitude": 37.77619239601622,
    "cameraHeight": 1228.9977924042103,
    "cameraDirX": 0.7840399820772174,
    "cameraDirY": -0.46728690071019036,
    "cameraDirZ": 0.4085636534605367,
    "cameraUpX": -0.04957088269002503,
    "cameraUpY": 0.6089792149835486,
    "cameraUpZ": 0.7916356758682322,
    "cameraRightX": -0.6187277544232912,
    "cameraRightY": -0.640926882056515,
    "cameraRightZ": 0.45430022866340913,
    "fov": 1.0471975511965976,
    "aspectRatio": 1.37108953613808,
    "nearPlane": 0.1,
    "farPlane": 10000000000,
    "centerLongitude": 112.70508689894325,
    "centerLatitude": 37.80214573996048,
    "centerHeight": 908.1472263126086,
    "heading": "324.92",
    "pitch": "-19.26",
    "roll": "0.00"
  },
  "clarity": 800
}

### Response
HTTP/1.1 200 OK
Server: TornadoServer/6.4.1
Content-Type: application/json; charset=UTF-8
Date: Thu, 07 Nov 2024 07:12:42 GMT
Content-Length: 141

{
  "project_zip_url": "http://localhost:80/jingweipy/test.zip",
  "image_url": "http://localhost:80/jingweipy/local/test-位置图.png"
}
###
